### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by faker2048** [faker2048/whisper-echo#7]
- [x] Compile whisper.cpp in the Nix environment and run the demo.
- [x] Wrap whisper context with simple C++ code.
- [x] Implement a WebSocket framework.
- [x] Create a simple API for WebSocket communication.
- [x] Write a python client examples.
- [ ] Add GPU support.
- [ ] Implement caching of parsed result text.
- [ ] Create a simple oneshot API.
- [ ] Enable user-defined model parameters via WebSocket messages.
